### ISSUE TITLE
Angular Basics

### ISSUE THREAD

**Issue by Sta7e** [johanngoltz/sumz-ui#4]
### ToDos
- [ ] Bevorzugte Entwicklungsumgebung einrichten (bspw. Visual Studio Code)
- [ ] Github Repository einbinden
- [ ] Angular Tutorial + Grundlagen verstehen
- [ ] Funktionalitäten sicherstellen: Startet die Angular-Beispielapp aus dem Repo?

### Sources
[https://stackoverflow.com/questions/40840317/angular2-how-to-start-and-with-which-ide](https://stackoverflow.com/questions/40840317/angular2-how-to-start-and-with-which-ide)
[https://angular.io/](https://angular.io/)

### Hinweise
- CLI Global installieren (s. Angular Getting Started)

### Deadline
Sonntag 13.05.2018
